# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: build
    steps:
      - task: PublishPipelineArtifact@1
        inputs:
          artifact: s.py
          path: $(System.DefaultWorkingDirectory)/s.py

- stage: deploy
  displayName: Deploy stage
  jobs:
  - deployment: VMDeploy
    displayName: web
    pool:
      vmImage: 'Ubuntu-16.04'

    environment:
      name: VultrJapan
      resourceType: virtualMachine
      tags: japan

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              path: /tmp
              artifact: s.py

          - script: |
              echo my first deployment
              python /tmp/s.py
